### ISSUE TITLE
Connection Refused (Dockbix-Agent-XXL to Zabbix Server on CentOS)

### ISSUE THREAD

**Issue by LawrenceIRL** [monitoringartist/kubernetes-zabbix#7]
I have the Dockbix-Agent-XLL daemonset running on our Kubernetes cluster here. This is connecting to our Zabbix Server, which is outside of Kubernetes.

However, I am getting this error: `active check configuration update from [IP:10051] started to fail (cannot connect to [[IP]:10051]: [111] Connection refused)`

If I try telnet on that Zabbix Server IP and on that port (10051), it works OK.

It appears, that I just need to change this section of the .yaml:
```
          env:
            - name: ZA_Server
              value: "_IP Address Here_"
            - name: ZA_ServerActive
              value: "_IP Address Here_"
```

Am I missing something? Thanks.
